---
title: "EDLD 2 - Lab 2"
author: "Ann-Marie Barrett, Raleigh Goodwin, Kavya Mudiam, Zachary Schroeder,  Vinita Vader"
date: "January 2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages, include=FALSE}
# try not to load packages twice or packages that you don't need in the script

library(fivethirtyeight)
library(fivethirtyeightdata)
library(tidyverse)
#library(ggplot2)
library(showtext)
#library(tidyverse)
library(lubridate)
library(rio)
library(here)
library(janitor)
library(stringr)
#library(forcats)
#library(ggplot2)
#library(lubridate)
library(ggforce)
library(ggthemes)
library(colorblindr)

```

# #1
```{r}
# Shouldn't need either of the lines below
# google_trends <- data.frame(google_trends)
# tv_states <- data.frame(tv_states)

# Pivoting data long to make easier to plot
google_trends_long <- google_trends %>% 
  mutate(Harvey = hurricane_harvey_us,
         Irma = hurricane_irma_us,
         Maria = hurricane_maria_us,
         Jose = hurricane_jose_us) %>% 
  select(date, Harvey, Irma, Maria, Jose)

# I'd suggest moving to pivot_longer, as I illustrated today
# Also, try to get in the habit of not going beyond 80 characters
# You can set a ruler to help this
# I would also not use T for TRUE because it can be overwritten, 
# e.g. T <- FALSE
google_trends_long <- gather(google_trends_long, 
                             "Hurricane", 
                             "Searches", 
                             Harvey:Jose, 
                             factor_key = TRUE) #

# First visualization

google_trends_long %>% 
  ggplot(aes(date, Searches)) + 
  geom_line(aes(color = Hurricane)) +
  labs(title = "2017 Hurricane Season Google Trends",
       x = "Date") + 
  theme_minimal()

# Visualization with solid shapes

plot <- google_trends_long %>% 
  ggplot(aes(date, Searches)) + 
  geom_ribbon(aes(ymin = 0, ymax = Searches, 
                  fill = Hurricane),
              alpha = .7) +
  labs(title = "2017 Hurricane Season Google Trends",
       x = "Date") +
  theme_minimal()

# Same relation but color continuous

google_trends_long %>% 
  #group_by(Hurricane, date) %>% 
  ggplot(aes(date, Hurricane)) +
  geom_tile(aes(fill = Searches), 
            color = "white") +
  coord_fixed() +
  scale_fill_viridis_c(direction = -1, option = "plasma")

# Landfall dates included

google_trends_landfall <- tibble(
  landfall = c(ymd(20170825), ymd(20170910), ymd(20170920)),
  storm = c("Harvey", "Irma", "Maria")
  )

plot + 
  geom_vline(data = google_trends_landfall, aes(xintercept = landfall)) + 
  geom_text(aes(x = ymd(20170825)+1, label = "Harvey landfall", y = 80, angle = 90)) +
  geom_text(aes(x = ymd(20170910)+1, label = "Irma landfall", y = 80, angle = 90)) +
  geom_text(aes(x = ymd(20170920)+1, label = "Maria landfall", y = 80, angle = 90))

#Final modifications 
google_trends_long %>% 
  ggplot(aes(date, Searches)) + 
  geom_ribbon(aes(ymin = 0, ymax = Searches, 
                  fill = Hurricane),
              alpha = .65) +
  geom_vline(data = google_trends_landfall, aes(xintercept = landfall)) + 
  geom_text(aes(x = ymd(20170825)+1, label = "Harvey landfall", y = 80, angle = 90)) +
  geom_text(aes(x = ymd(20170910)+1, label = "Irma landfall", y = 80, angle = 90)) +
  geom_text(aes(x = ymd(20170920)+1, label = "Maria landfall", y = 80, angle = 90)) +
  labs(title = "2017 Hurricane Season Google Trends",
       x = "Date") +
  scale_fill_viridis_d(option = "plasma") +
  theme_minimal() +
   theme(plot.title = element_text(size=17),
         axis.title.x = element_text(size=13),
         axis.title.y = element_text(size=13),
         axis.text = element_text(size=11))

# Looks nice! I'm not so sure about the labels on their side but 
# otherwise I like it
```

#Replicating National Cable News 
```{r}
tv_states_long <- pivot_longer(tv_states, c(florida, texas, puerto_rico))
# Comic Characters

# A dataframe for annotations
annot = data.frame(
  text = c("Texas", "Florida", "Puerto Rico"),
  x = lubridate::mdy(c("AUGUST 26, 2017",
                       "SEPTEMBER 7, 2017",
                       "SEPTEMBER 22, 2017")),
  y = c(0.80, 1.5, 1.5)
)

date <- c("2017-08-15","2017-08-15", "2017-08-15")
name <- c("texas", "florida", "puerto_rico")
value <- c(0,0,0)

aug15 <- data.frame(date, name, value)
aug15$date <- as.Date(aug15$date)
tv_states_long <- rbind(aug15, tv_states_long)

plot = tv_states_long %>%
    mutate(name = fct_relevel(name,
            "florida", "texas", "puerto_rico")) %>%
  ggplot(aes(x = date, y = value, group = name)) +
   geom_line()+
   geom_ribbon(aes(ymin=0, ymax = value, fill = name), color = "white")+
   scale_fill_manual(values = c("#FF33A8", "#FF8133", "#00AFBB"))+
   labs( y = "Share of sentences",
       title = "National cable news networks")+
   guides(fill=FALSE)+
   theme_minimal()+ 
   geom_hline(yintercept=0, size=.3) +
  geom_vline(xintercept = as.Date(tv_states_long$date[.75]), color = "grey90", size=.4) +
   geom_text(data = annot, aes(x=x, y=y, label = text), color="black", hjust=0, size=4, inherit.aes = FALSE, fontface = "bold")+

  
  
  geom_vline(aes(xintercept = as.Date(tv_states_long$date[18])), linetype="dotted", color = "grey90", size=.4)+ #first line
    annotate( x=as.Date(tv_states_long$date[16]),y=3,label= 'atop(italic("Harvey"),italic("landfall"))', geom="text", color = "grey", parse = TRUE, size = 3)+ #first anotate #HOW TO CHANGE LINE SPACE BETWEEN HARVEY LANDFALL
  
    geom_vline(aes(xintercept = as.Date(tv_states_long$date[68])), linetype="dotted", color = "grey90", size=.3) + #second line
  annotate( x=as.Date(tv_states_long$date[70]),y=3.2,label= 'atop(italic("Irma"),italic("landfall"))', geom="text", color = "grey", parse = TRUE, size = 3)+ #second anotate # HOW TO CHANGE LINE SPACE BETWEEN HARVEY LANDFALL
  
   geom_vline(aes(xintercept = as.Date(tv_states_long$date[98])), linetype="dotted", color = "grey90", size=.3) + #fourth line
   annotate( x=as.Date(tv_states_long$date[98]),y=2,label= 'atop(italic("Maria"),italic("landfall"))', geom="text", color = "grey", parse = TRUE, size = 3)+ #second anotate #HOW TO CHANGE LINE SPACE BETWEEN HARVEY LANDFALL
  
  geom_vline(aes(xintercept = as.Date(tv_states_long$date[130])), linetype="dotted", color = "grey90", size=.3)+ #third line
   annotate( x=as.Date(tv_states_long$date[130]),y=3,label= 'atop(italic("Las Vegas"), italic("shooting"))', geom="text", color = "grey", parse = TRUE, size = 3) + #second anotate #HOW TO CHANGE LINE SPACE BETWEEN HARVEY LANDFALL 
   scale_y_continuous(label=function(x){return(paste(x, "%"))})

myFont2 <- "mono"
plot + theme(panel.grid.minor = element_blank(), 
             panel.background = element_blank(),
             plot.title = element_text(size=11, face="bold", hjust = 0.5),
             axis.title.x = element_blank(),
             axis.title.y = element_text(size=11, face="bold"))#, family = 'mono'))
           #  text = element_text(size = 16, family = myFont2))

#font_families()
#text = element_text(size = 16, family = myFont1
#How to change the font for x-axis labels? KM: I wonder if we should change it to all caps in the dataframe... I'm not able to find how to change the font type 
#How to make annotate text italic? KM: done 
#How to keep the main title at the center?:done
#line spacing
#need to change the dotted line position to match with the solid lines. Got changed because we added Aug 15 into the x axis 

#FF8133 - orange
#00AFBB - blue
#FF33A8 - pink


# Looks amazing! Really well done.
```


```{r CC Data Cleaning & Variable Creation, include=FALSE}
#library(tidyverse)
#comic_characters <- data.frame(comic_characters)
#

# I'd suggest staying consistent and using the tidyverse throughout
#str(comic_characters)
comic_characters$gender <- factor(comic_characters$sex)
comic_characters$alive <- factor(comic_characters$alive)
comic_characters$fyear <- factor(comic_characters$year)
#comic_characters <- comic_characters %>%
 # mutate(month = round_date(data$created_at, # May want to add year variable
  #                          unit = "month"))
```

## Figure 1: Simple, not too helpful bar chart

```{r CC Figure 1, warning=FALSE}
comic_characters %>% 
  ggplot(aes(x = gender, fill = gender)) +
  geom_bar() +
  labs(title = "Number of Each Gender Identity Represented in Comic Books",
       subtitle = "A not-so-helpful figure",
       x = "Gender Identity",
       y = "N") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_OkabeIto() +
  guides(fill = "none") # could probably omit the legend here
```

## Figure 2: Line graph of sum over time with different line for genders

```{r CC Figure 2, warning=FALSE}
comic_characters %>% 
  group_by(gender) %>% 
  count(year) %>% 
  ggplot(aes(x = year, y = n, color = gender)) +
  geom_path() +
  labs(title = "Number of Each Gender Identity Introduced in Per Year",
       subtitle = "A somewhat helpful figure",
       x = "Year",
       y = "N",
       color = "Gender Identity")+
  scale_colour_OkabeIto()
```


## Change in Gender Representation Proportion Over Time

```{r CC Figure 3, warning=FALSE, message=FALSE}
cc <- comic_characters %>% 
  group_by(gender) %>% 
  group_by(fyear, .add = T) %>% 
  summarise(no_rows = length(year)) %>% # This creates a long df that counts the number of each gender per year
  spread(., key = fyear, value = no_rows) %>% #this creates a wide version by year
  t(.) %>% # Makes each gender identity a column
  data.frame(.) %>% 
  janitor::row_to_names(row_number = 1)
  
#Creating Column Names
colnames(cc) <- c("Agender", "Female", "Genderfluid", "Genderless", "Male", "Transgender", "NA_Gender")
#Saving Years
cc <- cc %>% 
  mutate(
    year = rownames(cc)
  )

# Making all columns numeric
cc <- mutate_all(cc, function(x) as.numeric(as.character(x))) %>% 
  filter(year != "NA")

# Replacing NAs with 0
cc[is.na(cc)] <- 0

# Calculating Cumsums
cc_cum <- cc %>% 
  mutate(
    Agender = cumsum(Agender),
    Female = cumsum(Female),
    Genderfluid = cumsum(Genderfluid),
    Genderless = cumsum(Genderless),
    Male = cumsum(Male),
    Transgender = cumsum(Transgender),
    NA_Gender = cumsum(NA_Gender)
  )

#Creating Loop to get row-wise proportions
cc_loop <- cc_cum[,1:6]
cc_prop <- cc_cum[,1:6]
for(j in 1:nrow(cc_loop)){
  for(i in 1:ncol(cc_loop)){
    cc_prop[j,i] <- (cc_loop[j,i]/rowSums(cc_loop[j,]))
  }
}
rm(cc_loop)

#Creating Long Dataframe
cc_prop$year <- cc_cum$year
cc_proplong <- gather(cc_prop, key = "year")
cc_proplong$yr <- rep(cc_cum$year, ncol(cc_prop)-1)
colnames(cc_proplong) <- c("Gender", "Prop", "Year")
cc_proplong$Gender <- factor(cc_proplong$Gender, 
                             levels = c("Male", "Female", "Agender",  
                                        "Genderfluid","Genderless", "Transgender"))
cc_proplong$scale <- c(rep("Non-Cis", nrow(cc_prop)),
                       rep("Cis", nrow(cc_prop)),
                       rep("Non-Cis", nrow(cc_prop)),
                       rep("Non-Cis", nrow(cc_prop)),
                       rep("Cis", nrow(cc_prop)),
                       rep("Non-Cis", nrow(cc_prop)))

cc_proplong %>% 
  ggplot(aes(x = Year, y = Prop, color = Gender)) +
  geom_line() +
  labs(title = "Proportional Gender Representation in Comics",
       subtitle = "Proportions calculated cumulatively",
       y = "Gender (Percent)",
       caption = "Data taken from 538's fivethirtyeightdata package") +
  theme_linedraw() +
  facet_zoom(ylim = c(0,0.002),
             zoom.size = 1,
             split = TRUE) +
  scale_colour_OkabeIto()

# I tried replicating your plot using just the tidyverse but I'm not
# able to. I'm not sure if I'm just not seeing something that you're
# doing or if one of us has an error but I wasn't ablt to get your 
# same plot. This is the approach I took

cummulative_props <- comic_characters %>% 
  count(year, gender) %>% 
  pivot_wider(names_from = "gender",
              values_from = n, 
              values_fill = 0) %>% 
  select(-`NA`) %>% # I dropped NA's because I didn't see them in yours, but I'm not sure this is ideal
  pivot_longer(-year,
               names_to = "Gender",
               values_to = "n") %>% 
  group_by(year, Gender) %>% 
  mutate(cummulative_n = cumsum(n)) %>% 
  group_by(year) %>% 
  mutate(Prop = cummulative_n/sum(n)) %>% # Proportion of each gender within each year - is that what you did?
  rename(Year = year)

cummulative_props %>% 
  ggplot(aes(x = Year, y = Prop, color = Gender)) +
  geom_line() +
  labs(title = "Proportional Gender Representation in Comics",
       subtitle = "Proportions calculated cumulatively",
       y = "Gender (Percent)",
       caption = "Data taken from 538's fivethirtyeightdata package") +
  theme_linedraw() +
  facet_zoom(ylim = c(0,0.05),
             zoom.size = 1,
             split = TRUE) +
  scale_colour_OkabeIto()
```

